/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package service;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.Test;

import com.model.*;
import com.service.AuthService;

public class AuthServiceTest {
	
	String userName = "yang";
	String psd = "1k200";
	String roleName = "guest";
	
	private User createTestUser(AuthService serviceTest) {
		return serviceTest.createUser(userName, psd);
	}
	
    @Test public void createUser() {
    	AuthService serviceTest = new AuthService();
    	User user1 = createTestUser(serviceTest);
    	assertEquals(userName, user1.getUsername());
    }
    
    @Test public void deleteUser() {
    	AuthService serviceTest = new AuthService();
    	createTestUser(serviceTest);
    	serviceTest.deleteUser(userName);
    	User result = serviceTest.getUser(userName);
    	assertNull("Delete user", result);
    }
    
    private Role createTestRole(AuthService serviceTest) {
    	return serviceTest.createRole(roleName);
    }
    
    @Test public void createRole() {
    	AuthService serviceTest = new AuthService();
    	Role role = createTestRole(serviceTest);
    	assertEquals(roleName, role.getRoleName());
    }
    
    @Test public void deleteRole() {
    	AuthService serviceTest = new AuthService();
    	Role role = createTestRole(serviceTest);
    	serviceTest.deleteRole(roleName);
    	List<String> results = serviceTest.getRoles(roleName);
    	int re = results == null? 0 : results.size();
    	assertEquals(0, re);
    }
    
    
    @Test public void authenticate() {
    	AuthService serviceTest = new AuthService();
    	String userName = "yang";
    	String psd = "1k200";
    	User user = serviceTest.createUser(userName, psd);
    	
    	String token = serviceTest.authenticate(userName, psd);
    	assertNotNull("Generate token", token);
    }
    
}
